
CREATE TABLE CURSO(
CODIGO INT PRIMARY KEY,
NOMBRE VARCHAR (25) NOT NULL,
DESCRIPCION VARCHAR,
TURNO VARCHAR (10) NOT NULL
);

ALTER TABLE CURSO ADD COLUMN CUPO INT;

INSERT INTO CURSO VALUES
(101,"Algoritmos","Algoritmos y Estructuras de Datos","Mañana",35),
(102,"Matemática Discreta","","Tarde",30);

INSERT INTO CURSO VALUES
(103,NULL,"","Tarde",30);
INSERT INTO CURSO VALUES
(102,"Algoritmos 2","","Tarde",30);

UPDATE CURSO SET CUPO=25;

DELETE FROM CURSO WHERE CODIGO=101;